config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources  :listings do
    resources :orders, only: [:new, :create]		
	end
	resource :contacts, only: [:new, :create], path_names: { new: '' }
	
  get 'pages/about'
  get 'seller'    => 'listings#seller'
  get 'sales'     => 'orders#sales'
  get 'purchases' => 'orders#purchases'
  
  root 'listings#index'
  

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :listings
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :email, :message, presence: true
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file :image, styles: { medium: "200x", thumb: "100x100>" }, default_url: "default.jpg"
	else
	  has_attached_file :image, styles: { medium: "200x", thumb: "100x100>" }, default_url: "default.jpg",
	                    :storage             => :dropbox,
                      :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                      :path                => ":style/:id_:filename"
  end
                    
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates_attachment_presence :image
  
  belongs_to :user
  belongs_to :category
  has_many   :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :address, :city, :state, presence: true
  
  belongs_to :listing
  belongs_to :buyer,  class_name: "User"
  belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :name, presence: true
  
  has_many :listings,  dependent: :destroy
  has_many :sales,     class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	
	def new
		@contact = Contact.new
	end
	
	def create
		@contact = Contact.new(contact_params)
		if @contact.save
	    redirect_to root_url, notice: 'Thanks! We receive your message.'
	  else
	    render :new
	  end
	end
	
	private 
	  def contact_params 
	    params.require(:contact).permit(:email, :message)
	  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :set_listing, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
	before_filter :check_user, only: [:edit, :update, :destroy]
	
	def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")		
	end
	
	def index
		if params[:category].blank?
	    @listings = Listing.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
	  else
      @category_id = Category.find_by(name: params[:category]).id
      @listings = Listing.where(category_id: @category_id).order("created_at DESC").paginate(:page => params[:page], :per_page => 12)	  
	  end
	end
	
	def show;  end
	
	def new
    @listing = Listing.new		
	end
	
	def create
		@listing = Listing.new(listing_params)
		@listing.user_id = current_user.id
		
		if current_user.recipient.blank?
			Stripe.api_key = ENV["STRIPE_API_KEY"]
	    token = params[:stripeToken]
	    
	    recipient = Stripe::Recipient.create(
		    :name         => current_user.name,
		    :type         => "individual",
		    :bank_account => token
	    )
	  end
    
    current_user.recipient = recipient.id
    current_user.save
    
		if @listing.save
			redirect_to @listing, notice: 'Listing was successfully created.'
		else
		  render :new
		end
	end
	
	def update
		if @listing.update(listing_params)
			redirect_to @listing, notice: 'Listing was successfully updated.' 
		else
		  render :edit
		end
	end
	
	def destroy
		@listing.destroy
		redirect_to listings_url, notice: 'Listing was deleted.'
	end
  
  private	
  
    def set_listing
	    @listing = Listing.find(params[:id])
	  end
	  
	  def listing_params
		  params.require(:listing).permit(:name, :category_id, :description, :price, :image)
		end
		
		def check_user
      if current_user != @listing.user
	      redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
	    end
		end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :set_order, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!
	
	def sales
    @orders = Order.all.where(seller: current_user).order('created_at DESC')		
	end
	
	def purchases
    @orders = Order.all.where(buyer: current_user).order('created_at DESC')		
	end
	
	def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])		
	end
	
	def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user
    
    @order.listing_id = @listing.id
    @order.buyer_id   = current_user.id
    @order.seller_id  = @seller.id
    
    Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]
    
    begin
	    charge = Stripe::Charge.create(
		    :amount   => (@listing.price * 100).floor,
		    :currency => "usd",
		    :card     => token
	      )
	    flash[:notice] = "Thanks for ordering!"
	  rescue Stripe::CardError => e
	    flash[:danger] = e.message
	  end
	  
	  transfer = Stripe::Transfer.create(
		  :amount    => (@listing.price * 95).floor,
		  :currency  => "usd",
		  :recipient => @seller.recipient
	  )
    
    if @order.save
	    redirect_to root_url
	  else
	    render :new
	  end		
	end
	
	private	
  
    def set_order
	    @order = Order.find(params[:id])
	  end
	  
	  def order_params
		  params.require(:order).permit(:address, :city, :state)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return '' if resource.errors.empty?
		
		messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
		sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)
		
		html = <<-HTML
			<div class="alert alert-warning alert-dismissable">
			  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			  <h4>#{sentence}</h4>
			  #{messages}
			</div>
			HTML
			
			html.html_safe
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation" class="alert alert-warning alert-dismissable">
	    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@contact.errors.count, "error") %> prohibited this form from being send:</h4>
      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
	<form class="form-horizontal">
	  <div class="form-group col-xs-7">
		  <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
	  </div>
	  <div class="form-group col-xs-7">
		  <%= f.label :message %>
      <%= f.text_area :message, class: "form-control" %>
	  </div>
	  <div class="form-group col-xs-7">
	    <%= f.submit class: "btn btn-info", value: "Send" %>
	  </div>
  </form>
<% end %>

app/views/contacts/new.html.erb
<h3>Contact Us</h3>

<%= render 'form' %>

<div class="col-xs-7">
  <%= link_to 'Back', root_path, class: "btn btn-link" %>
</div>

app/views/layouts/_facebook.html.erb
<div id="fb-root"></div>
    <script>
	    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_EN/sdk.js#xfbml=1&version=v2.5";
        fjs.parentNode.insertBefore(js, fjs);
      }
      (document, 'script', 'facebook-jssdk'));
    </script>

app/views/layouts/_footer.html.erb
<footer>
	<div class="footer navbar-fixed-bottom">
		<div class="text-center" id="footer">
      <p><em>Developed by 7rka.com</em></p>
		</div>	
	</div>
</footer>

app/views/layouts/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-inverse" role="navigation">
	<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Menu</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">LegoMarket</a>
  </div>
  <div class="navbar-collapse collapse">
	  <ul class="nav navbar-nav">
		  <li><%= link_to "About", pages_about_path %></li>
		  <li><%= link_to "Contact", contacts_path %></li>
		  <li class="dropdown">
	        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse <b class="caret"></b></a>
	        <ul class="dropdown-menu">
		        <% Category.all.each do |category| %>
		          <li><%= link_to category.name, listings_path(category: category.name) %></li>
		        <% end %>
	        </ul>
	      </li>
	  </ul>
    <ul class="nav navbar-nav navbar-right">
	    <% if user_signed_in? %>
	      <li class="dropdown">
	        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Seller Account <b class="caret"></b></a>
	        <ul class="dropdown-menu">
		        <li><%= link_to "Manage Listings", seller_path %></li>
		        <li><%= link_to "Sales History", sales_path %></li>
	        </ul>
	      </li>
	      
	      <li class="dropdown">
	        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
	        <ul class="dropdown-menu">
		        <li><%= link_to "Purchase History", purchases_path %></li>
		        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
	        </ul>
	      </li>
	    <% else %>
	      <li><%= link_to "Sign Up", new_user_registration_path %></li>
	      <li><%= link_to "Login", new_user_session_path %></li>
	    <% end %>
    </ul>
  </div><!--/.nav-collapse -->
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LegoMarket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://js.stripe.com/v2/'%>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
	  <% if msg.is_a?(String) %>
	    <div class="alert alert-<%= name == :notice ? "warning" : "success" %> alert-dismissable" role="alert">
		    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
	    </div>
	  <% end %>
	<% end %>
  <%= yield %>
</div>
<br>
<%= render 'layouts/footer' %>
<%= render 'layouts/facebook', data: { no_turbolink: true } %>
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, html: { multipart: true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-warning alert-dismissable">
	    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>
      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div id="stripe_error" class="alert alert-danger" style="display:none">
	  <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
	</div>
  
	<form class="form-horizontal">
	  <div class="form-group col-xs-7">
		  <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
	  </div>
	  <div class="form-group col-xs-7">
		  <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category"}, { class: "btn btn-info dropdown-toggle form-control" } %>
	  </div>
	  <div class="form-group col-xs-7">
		  <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
	  </div>
	  <div class="form-group col-xs-7">
		  <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
	  </div>
	  <div class="form-group col-xs-7">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
      <p class="help-block">Choose image to download</p>
    </div>
    
    <% if current_user.recipient.blank? %>
	    <div class="col-xs-7">
	      <h4>Bank Account Information</h4>
	    </div>
	    <div class="form-group col-xs-7">
			  <%= label_tag :country %>
	      <%= text_field_tag :country, nil, { :name => nil, :"data-stripe" => "country", class: "form-control" } %>
		  </div>
		  <div class="form-group col-xs-7">
			  <%= label_tag :routing_number %>
	      <%= text_field_tag :routing_number, nil, { :name => nil, :"data-stripe" => "routingNumber", class: "form-control" } %>
		  </div>
		  <div class="form-group col-xs-7">
			  <%= label_tag :account_number %>
	      <%= text_field_tag :account_number, nil, { :name => nil, :"data-stripe" => "accountNumber", class: "form-control" } %>
	    </div>
	  <% end %>
	  <div class="form-group col-xs-7">
	    <%= f.submit class: "btn btn-warning" %>
	  </div>
  </form>
  
<% end %> 

app/views/listings/edit.html.erb
<h3>Editing Listing</h3>
  <%= render 'form' %>
<div class="col-xs-7">
  <%= link_to 'Show', @listing, class: "btn btn-link" %> |
  <%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div>

app/views/listings/index.html.erb
<div class="jumbotron">
		<h3 class="text-center">Online Lego Market</h3>
		<p class="text-center">Here you can buy or sell Lego</p>
</div>
<div class="row text-center">
  <% @listings.each do |listing| %>
    <div class="col-xs-3">
	    <div class="thumbnail">
		    <%= link_to image_tag(listing.image.url), listing %>
        <div class="caption">
          <h4><%= listing.name %></h4>
          <p><%= number_to_currency(listing.price) %></p>
          <p><%= "Sold by #{listing.user.name}" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

  <%= will_paginate @listings, renderer: BootstrapPagination::Rails %> 

<br>

<% if user_signed_in? %> 
  <%= link_to new_listing_path, class: "btn btn-primary", data: { no_turbolink: true } do %>
    <i class="glyphicon glyphicon-plus"></i> New Listing
  <% end %>
<% end %>

app/views/listings/new.html.erb
<h3>New Listing</h3>

<%= render 'form' %>

<div class="col-xs-7">
  <%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div>

app/views/listings/seller.html.erb
<table class="table table-hover">
	<tr>
		<th class="center">Image</th>
		<th class="center">Name</th>
		<th class="center">Description</th>
		<th class="center">Price</th>
		<th class="center">Action</th>
	</tr>
  <% @listings.each do |listing| %>
    <tr>
	    <td><%= image_tag listing.image.url(:thumb) %></td>
	    <td><%= listing.name %></td>
	    <td><%= listing.description %></td>
	    <td><%= number_to_currency(listing.price) %></td>
	    <td>
		    <div class="btn-group">
			    <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
			      Action <span class="caret"></span>
			    </button>
			    <ul class="dropdown-menu" role="menu">
	          <li><%= link_to "view", listing, class: "btn btn-link" %></li>
				    <li><%= link_to "edit", edit_listing_path(listing), class: "btn btn-link" %></li>
				    <li><%= link_to "destroy", listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
			    </ul>
		    </div>
	    </td>
    </tr>
  <% end %>
</table>

<% if user_signed_in? %>    
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: { no_turbolink: true } %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
	<div class="col-xs-6">
		<div class="thumbnail">
		  <%= image_tag @listing.image.url %>
		</div>
	</div>
	<div class="col-xs-6">
		<h3><%= @listing.name %></h3>
		<p><%= number_to_currency(@listing.price) %></p>
		<p><%= @listing.description %></p>
		<div class="fb-like" data-href="https://legomarket.herokuapp.com" data-layout="button" data-action="like" data-show-faces="false" data-share="false">
    </div>
    <br>
		<div class="text-center">
      <%= link_to "Buy It Now", new_listing_order_path(@listing), class: "btn btn-primary", data: { no_turbolink: true } %>
    </div>
	</div>
</div>

<div class="row">
	<div class="col-xs-7">
		<% if current_user == @listing.user %> 
	    <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
	  <% end %>
	  <%= link_to 'Back', listings_path, class: "btn btn-link" %>
	</div>
</div>

app/views/orders/_form.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-4 col-md-4">
		<div class="thumbnail">
		  <%= image_tag @listing.image.url %>
		</div>
		<h3><%= @listing.name %></h3>
		<h4><%= number_to_currency(@listing.price) %></h4>
	</div>
	<div class="col-xs-12 col-sm-8 col-md-8">
		<%= form_for([@listing, @order], html: { multipart: true }) do |f| %>
		  <% if @order.errors.any? %>
		    <div id="error_explanation" class="alert alert-warning alert-dismissable">
			    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>
		      <ul>
		      <% @order.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		  
		  <div id="stripe_error" class="alert alert-danger" style="display:none">
			  <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
		  </div>
	
			<form class="form-horizontal">
			  <div class="form-group">
				  <%= f.label :address %>
		      <%= f.text_field :address, class: "form-control" %>
			  </div>
			  <div class="form-group">
				  <%= f.label :city %>
		      <%= f.text_field :city, class: "form-control" %>
			  </div>
			  <div class="form-group">
				  <%= f.label :state %>
		      <%= f.text_field :state, class: "form-control" %>
			  </div>
			  <div class="form-group">
			    <div class="row">
			      <div class="col-xs-8">
				      <%= label_tag :card_number, "Credit Card Number" %>
		          <%= text_field_tag :card_number, nil, { :name => nil, :"data-stripe" => "number", class: "form-control" } %>
			      </div>
			      <div class="col-xs-4">
				      <%= label_tag :card_code, "CVC" %>
		          <%= text_field_tag :card_code, nil, { :name => nil, :"data-stripe" => "cvc", class: "form-control" } %>
			      </div>
			    </div>
			  </div>
			  <div class="form-group">
				  <%= label_tag nil, "Expiration Date" %>
				  <div class="row">
					  <div class="col-xs-4">
				      <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :"data-stripe" => "exp-month", class: "form-control" } %>
				    </div>
					  <div class="col-xs-4">
						  <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :"data-stripe" => "exp-year", class: "form-control" } %>
					  </div>
				  </div>
			  </div>
			  <div class="form-group">
			    <%= f.submit "Complete Order", class: "btn btn-success" %>
			  </div>
		  </form>
		<% end %>
	</div>
</div> 

app/views/orders/new.html.erb
<%= render 'form' %>

<div class="col-xs-7">
  <%= link_to 'Back', @listing, class: "btn btn-link" %>
</div>

app/views/orders/purchases.html.erb
<div class="text-center">
	<h3>Your Purchase History</h3>
</div>
<table class="table table-hover">
	<tr>
		<th class="center">Image</th>
		<th class="center">Item</th>
		<th class="center">Price</th>
		<th class="center">Seller</th>
		<th class="center">Date Purchased</th>
	</tr>
  <% @orders.each do |order| %>
    <tr>
	    <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
	    <td class="center"><%= order.listing.name %></td>
	    <td class="center"><%= number_to_currency(order.listing.price) %></td>
	    <td class="center"><%= order.seller.name %></td>
	    <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
    </tr>
  <% end %>
</table>

<% if user_signed_in? %>    
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: { no_turbolink: true } %>
<% end %>

app/views/orders/sales.html.erb
<div class="text-center">
	<h3>Your Sales History</h3>
</div>
<table class="table table-hover">
	<tr>
		<th class="center">Image</th>
		<th class="center">Item</th>
		<th class="center">Price</th>
		<th class="center">Customer</th>
		<th class="center">Date Sold</th>
	</tr>
  <% @orders.each do |order| %>
    <tr>
	    <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
	    <td class="center"><%= order.listing.name %></td>
	    <td class="center"><%= number_to_currency(order.listing.price) %></td>
	    <td class="center"><%= order.buyer.name %></td>
	    <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
    </tr>
  <% end %>
</table>

<% if user_signed_in? %>    
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: { no_turbolink: true } %>
<% end %>

app/views/pages/about.html.erb
<h3>Welcome to Market!</h3>
<p>Market is an online store for buying and selling goods</p>

app/views/pages/contact.html.erb
<h3>Contact Us</h3>
<p>You can send an email to us here.</p>